version: "3"
services:
    fast:
        build: .
        ports: 
            - 8000:8000 
        environment:
            - DATABASE_USERNAME=postgres
            - DATABASE_NAME=fastapi
            - DATABASE_PASSWORD=admin
            - DATABASE_PORT=5432
            - DATABASE_HOSTNAME=db  # Assuming your PostgreSQL service is named "db" in your Docker Compose network
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=60
        depends_on:
            - db

    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=fastapi
        ports:
            - "1432:5432"

    
